function* gen() { while(true) { try {yield 42; } catch(e) { console.log("Error caught!"); } } }
var g = gen();
 g.next();
  // { value: 42, done: false } 
	g.throw(new Error("Something went wrong"));